### ISSUE TITLE
Web view support

### ISSUE THREAD

**Issue by aurasphere** [BotMill/fb-botmill#10]
We should add support for web view. Here's Facebook documentation on this: https://developers.facebook.com/docs/messenger-platform/messenger-extension. I haven't looked into details yet.

**Comment by alvin-reyes** [comment]
I already implemented some of the components for this. I'm working on the white listing of domains now. Once I got that working, I'll be able to test this feature.

**Comment by alvin-reyes** [comment]
Completed this with the latest commit.
