### ISSUE TITLE
Missing Thread settings

### ISSUE THREAD

**Issue by aurasphere** [BotMill/fb-botmill#12]
We are missing some thread settings. These are really easy to implement. The references are here:

Payment: https://developers.facebook.com/docs/messenger-platform/thread-settings/payment
Account Linking: https://developers.facebook.com/docs/messenger-platform/thread-settings/account-linking
Domain Whitelisting: https://developers.facebook.com/docs/messenger-platform/thread-settings/domain-whitelisting

**Comment by Aurasphere** [comment]
@alvin-reyes the domain whitelisting is on this issue. If you are working on that, let me know here when you are done, so I'll remove it from the TODO list. Thank you!

**Comment by alvin-reyes** [comment]
Sure! Thanks!

**Comment by alvin-reyes** [comment]
Account linking and domain whitelisting is done.

**Comment by aurasphere** [comment]
I think this is done, right? @alvin-reyes  Can we close it?

**Comment by alvin-reyes** [comment]
Yes we can close this.
