### ISSUE TITLE
MessengerProfileApi and PersistentMenu are not found

### ISSUE THREAD

**Issue by kravchenko-rn** [BotMill/fb-botmill#121]
MessengerProfileApi and PersistentMenu classes are not found in the framework.
I tried to use 2.0.0-RC1 version.
So initialize() method, which is provided in readme.md will not work.
I imported the framework as a dependency via Maven.

**Comment by hendrixc** [comment]
All package botmill.fb.api is not present in 2.0.0-RC1 version. 
It is impossible for me, continue with example code.
I try to download source code and compile but this code make reference to botmil-core-1.0.2-SANPSHOT and I cant find this version to download.

**Comment by alvin-reyes** [comment]
Hi all.

Im working on a new version of facebook botmill that ill release tonight.

This should resolve the issue.

Thank you.

**Comment by kravchenko-rn** [comment]
Hi Alvin,
is there any chance to get the botmill.fb.api package back or any workaround that will allow to create a menu?

**Comment by alvin-reyes** [comment]
Please use the latest version of Fb-BotMill (2.0.0-RC2). This issues should be fixed by the latest version. Feel free to message me here if there are any issues.

**Comment by kravchenko-rn** [comment]
Thanks Alvin!
Tried to use 2.0.0-RC2 but seems like pageToken and validationToken are not being set up.
Those tokens are specified in `botmill.properties` which is in `src\main\resources` folder and it worked fine in 2.0.0-RC1.
I get this error in log:

> FbBotMill validation error: Page token can't be null or empty! Have you called the method FbBotMillContext.getInstance().setup(String, String)?

I tried to put a breakpoint on the first line of this method but it never stopped there so it's never called.
Please take a look at this.

**Comment by kravchenko-rn** [comment]
There's another problem.
Method `handleOutgoingMessage(MessageEnvelope message)` in the `IncomingToOutgoingMessageHandler` class has this line:
`Iterator var3 = ConfigurationUtils.getBotDefinitionInstances().iterator();`.
But the `ConfigurationUtils` class does not have such method `getBotDefinitionInstances()`.

**Comment by alvin-reyes** [comment]
Please get the latest version (RC2) and go thru the read me file. We included another step that will handle the one time configuration (persistent menus, bot authentication with page and validation token, etc).

**Comment by alvin-reyes** [comment]
I managed to get this working on the latest version. Please create another ticket if the issue persisted on your end.
