### ISSUE TITLE
Introduce a SpringBoot context 

### ISSUE THREAD

**Issue by alvin-reyes** [BotMill/fb-botmill#27]
We need to introduce a SprintBoot context to handle the get and post callbacks. This will be an alternative for developers that doesn't want to use web.xml/xml or servlet configuration.

**Comment by aurasphere** [comment]
Marked as wontfix (See #26 )

**Comment by Manojjanaka** [comment]
I got the fb-botmill configured with SpringBoot and You can find the sample project [here](https://github.com/Manojjanaka/spring-boot-with-fb-botmill)
