### ISSUE TITLE
Reply is not UTF-8 encoded

### ISSUE THREAD

**Issue by etteget** [BotMill/fb-botmill#38]
If reply contains for example Scandinavian or Spanish "special" characters, they are shown incorrectly. Example:

```
String test = "For example Scandinavian characters: työssä, Spanish: Habitación.";
return ReplyFactory.addTextMessageOnly(test).build(envelope);
```
**Result in Messenger**: For example Scandinavian characters: ty?ss?, Spanish: Habitaci?n.
**Expected result in Messenger**: For example Scandinavian characters: työssä, Spanish: Habitación.
**Potential fix:** In NetworkUtils::toStringEntity replace `input = new StringEntity(json);` with `input = new StringEntity(json, "UTF-8");`
**Other things that may affect to the result in Messenger**: User seeing the problem has locale fi_FI. Not tested with other user locales.
**Other**: Request seems to handle these "special" characters correctly.

**Comment by aurasphere** [comment]
Thank you for notifying us. This issue has been verifyed and solved.  It will be fixed soon in 1.1.0.
