### ISSUE TITLE
Error Handling / Network traffic and communication monitor

### ISSUE THREAD

**Issue by aurasphere** [BotMill/fb-botmill#39]
I was thinking of introducing a new feature that will improve the network handler. Basicallly I will add a `registerNetworkMonitor(FbBotMillNetworkMonitor)` on the `FbBotMillContext`.  `FbBotMillNetworkMonitor` is an interface with two methods: `onResponse(FbMessengerCallback)` and `onError(FacebookErrorMessage)`. Each of this methods will be used as a callback when a message is received from the Messenger platform, according to the kind of message. This will make the developers access data that are otherwise unavailable and may be useful in some situations. This will also be really good for unit testing.

**Comment by alvin-reyes** [comment]
Yes. We can then plug an analytics module so that we can track all of the information for a specific user.
