### ISSUE TITLE
About introducing EmptyReply and AWS Lambda Context

### ISSUE THREAD

**Issue by mrsfy** [BotMill/fb-botmill#43]
Thank you for this awesome work.

I want to contribute to an empty response type. Namely, an EmptyAutoReply class. For this type of response, nothing will be sent to facebook but there will be some changes applied on server. I needed it to achieve state management with a better software design. And currently for this purpose, I am using new ActionAutoReply(TypingAction.TYPING_OFF).

If you want, I can make pull requests by the following usage:
```
addActionFrame(event, new MessageAutoReply("just message"), new EmptyReply(){

        @Override
        public void createEmptyResponse(MessageEnvelope envelope) {
                // do something here
        }
    }
});
```

Also, I want to make pull request for AWS Lambda context(which I already have done) and its setup guidelines.

So, what is your opinion?

**Comment by alvin-reyes** [comment]
Hi @mrsfy. I see that you've made some awesome enhancements! That's fantastic and we really appreciate it! Please do a pull request so that we can review.

**Comment by alvin-reyes** [comment]
Hi @mrsfy. Just want to revisit your implementation again. Feel free to create a pull request if you are ready. Thank you!

**Comment by alvin-reyes** [comment]
Hi @mrsfy. Just want to revisit your implementation. We haven't heard back from you regarding this. Please advise if we can close this issue.
