### ISSUE TITLE
Multiple response on a single user input

### ISSUE THREAD

**Issue by alvin-reyes** [BotMill/fb-botmill#6]
It would be nice to add the possibility of adding more AutoReply in response to one event. This can be achieved at the moment by adding more action frames with the same event and setting the FaceBotPolicy to PROCESS_ALL. This works fine but there should be a method which takes as parameters one event and more AutoReply which does this automatically for you. Also, this may be applied the other way around with a method which takes only one AutoReply and binds it to multiple events.

**Comment by Aurasphere** [comment]
I've added more details on your comment in order to better keep track of what are we doing! Let me know what you think about the method which does the opposite! :)

**Comment by alvin-reyes** [comment]
Implemented in V1.0.0
