### ISSUE TITLE
Introduce log4j configuration 

### ISSUE THREAD

**Issue by alvin-reyes** [BotMill/fb-botmill#64]
We need to limit/control the logs being generated by the bot.

**Comment by aurasphere** [comment]
You can already do this with logback. You need to put a logback.xml file on your app classpath and you can configure the logger for the package co.aurasphere.botmill. Here's an example: 

    <logger name="co.aurasphere.botmill" level="DEBUG">
		<appender-ref ref="consoleAppender" />
    </logger>
