### ISSUE TITLE
WebView Customized Sharing

### ISSUE THREAD

**Issue by alvin-reyes** [BotMill/fb-botmill#92]
https://developers.facebook.com/docs/messenger-platform/webview

**Comment by aurasphere** [comment]
This seems to be out of scope for the framework (I don't even see an endpoint to where send the request) and only used on Facebook's own library. If you can confirm that, we can close this issue: https://developers.facebook.com/docs/messenger-platform/webview/sharing. Thank you.

**Comment by alvin-reyes** [comment]
Thanks for the clarification. We can close this one then.
